modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL = "https://github.com/AlexNijjar/${github_name}/issues"

[[mods]]
modId = "extractinator"
version = "${version}"
displayName = "Extractinator"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/extractinator"
logoFile = "icon.png"
authors = "Alex Nijjar, Kekie6"
credits = ""
description = "Convert blocks into resources."

[[dependencies.extractinator]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[${resourcefulconfig_version},)"
ordering = "NONE"
side = "BOTH"