modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL = "https://github.com/alexnijjar/extractinator/issues"

[[mods]]
modId = "extractinator"
version = "${version}"
displayName = "Extractinator"
displayURL = "https://modrinth.com/mod/extractinator"
logoFile = "icon.png"
authors = "Alex Nijjar"
credits = "Kekie6"
description = "Convert blocks into resources."

[[dependencies.extractinator]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "resourcefullib"
mandatory = true
versionRange = "[1.3.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extractinator]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "NONE"
side = "BOTH"