name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [ bug ]
body:
  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce?
      description: Steps to reproduce the behavior. Do not send exit codes, send the actual log
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the mod are you on?
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    id: loader-version
    attributes:
      label: Mod Loader Version
      description: What version of the mod loader are you on?
      placeholder: 1.20.1 - 47.1.3
    validations:
      required: true

  - type: dropdown
    id: loader
    attributes:
      label: Mod Loader
      description: What mod loader are you using?
      multiple: true
      options:
        - N/A
        - Forge
        - NeoForge
        - Fabric
        - Quilt
    validations:
      required: false

  - type: textarea
    id: logs-extra-context
    attributes:
      label: Logs or additional context
      description: Please copy and paste any relevant log output into a paste website such as [Pastebin](https://pastebin.com) and then link them here. You may also give any additional information here too.


  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree that you have done your due diligence and done the following
      options:
        - label: I have searched the issue tracker and confirmed that the issue has not been reported
          required: true
        - label: I have verified that I am using the latest version of the mod
          required: true
        - label: I have verified that I have installed all the required dependencies for the mod
          required: true
        - label: I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.
          required: true
