blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.terrarium.earth/
    about: If you have any questions about anything go here and ask. Otherwise click one of the templates above to report your problem.