name: Release
on: [
  workflow_dispatch
]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: chmod +x ./gradlew

      - name: Release
        run: ./gradlew :fabric:modrinth :forge:modrinth :fabric:curseforge :forge:curseforge
        env:
          CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}